name: Patch-Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    - name: Prepare Environment
      run: |
        sudo apt update
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Download Recovery Image
      run: |
        wget https://we.tl/t-MKbgvT5uQT -O recovery.img  # Descarga el archivo de la URL y lo renombra como recovery.img

    - name: Verify Recovery Image
      run: |
        if [ ! -f recovery.img ]; then
          echo "recovery.img not found!"
          exit 1
        fi
        ls -lh recovery.img

    - name: Patch Recovery Image
      run: |
        chmod a+x magiskboot
        ./magiskboot --patch recovery.img recovery-patched.img  # Reemplaza con el comando de parche que necesites

    - name: Verify Patched Recovery Image
      run: |
        if [ ! -f recovery-patched.img ]; then
          echo "recovery-patched.img not found!"
          exit 1
        fi
        ls -lh recovery-patched.img

    - name: Package Patched Recovery
      run: |
        mkdir output && mv recovery-patched.img output/
        tar cvf output/fastbootd-recovery.tar output/recovery-patched.img
        md5sum output/fastbootd-recovery.tar > output/fastbootd-recovery.tar.md5

    - name: Upload Patched Recovery
      uses: actions/upload-artifact@v3
      with:
        path: output/*
        name: Patched-Recovery
